name: protein-diffusion

dependencies:
    - dataclasses
    - toolz
    - numpy
    - pandas
    - pandas
    - tqdm
    - matplotlib
    - torchmetrics
    - pytorch
    - pip: 
        - hydra-core
        - omegaconf
        - biopython