data_config:
  train_data_path: /app/data/chain_set.jsonl
  validation_data_path:
  hf_data_path: # dataset path on huggingface
  max_seq_len: 256

model_config:
  timesteps: 1000
  beta_start: 1e-4
  beta_end: 2e-2

training_config:
  lr: 3e-4
  epochs: 2
  batch_size: 16
  shuffle_dataloader: True

scheduler_config:
  use_scheduler: True
  max_lr: 3e-3
  final_div_factor: 1000
  div_factor: 30
  

