data_config:
  data_file_path: /app/data/chain_set.jsonl
  splits_file_path: /app/data/chain_set_splits.json
  max_seq_len: 256

model_config:
  timesteps: 1000
  beta_start: 1e-4
  beta_end: 2e-2

training_config:
  lr: 3e-4
  epochs: 10
  batch_size: 16
  shuffle_dataloader: True

scheduler_config:
  use_scheduler: True
  max_lr: 3e-3
  final_div_factor: 1000
  div_factor: 30
  

