data_config:
  data_file_path:
  splits_file_path:
  max_seq_len:

Model_config:
  timespteps:
  beta_start:
  beta_end:

training_config:
  lr:
  epochs:
  batch_size:
  shuffle_dataloader: 

scheduler_config:
  use_scheduler:
  final_div_factor:
  

